### ISSUE TITLE
Is continuous maintenance?

### ISSUE THREAD

**Issue by t2y** [OddBloke/sphinx-git#24]
Hi, Sphinx-git extension provides a great feature, and then I think it has potential to be more powerful. For example, there're Python 3 support, commit diff function and so on.

Now it seems this project is not active. So can I help the maintenance work if you need.

**Comment by OddBloke** [comment]
Hi t2y,

I don't have cause to use sphinx-git in my current job, so it's largely in maintenance mode; I'd happily accept patches which provide the above (and will try to be better about responding to them).


Dan

**Comment by t2y** [comment]
Thank you for reply. I'll help this project!

Firstly, I need Python 3 support. Though there's #23, I think it needs some improvements. So I'm going to fix and send another PR.
