### ISSUE TITLE
How to run test code

### ISSUE THREAD

**Issue by t2y** [OddBloke/sphinx-git#25]
I tried to run test code in *tests* directory, but I couldn't. Sorry, I'm not sure about unittest module since I usually use *pytest* as a tset tool.

* https://docs.python.org/2.7/library/unittest.html

I tried like this. Could you tell me how to run it?

```shell
$ python setup.py test
$ python -m unittest discover
$ python -m unittest tests.test_git_changelog
```

**Comment by OddBloke** [comment]
This project uses nose, so you run the tests like this:

$ nosetests
.............
----------------------------------------------------------------------
Ran 13 tests in 0.588s

OK

**Comment by t2y** [comment]
I did it. Thanks!
