### ISSUE TITLE
Error with paths

### ISSUE THREAD

**Issue by tfvtfv** [OddBloke/sphinx-git#37]
Message told me to report it

This was my hello world example with sphinx-git
[sphinx-err-zs9ylu.zip](https://github.com/OddBloke/sphinx-git/files/476526/sphinx-err-zs9ylu.zip)

**Comment by OddBloke** [comment]
@tfvtfv Thanks for reporting this issue. As I've taken so long to respond (sorry!), I'm going to close this out.

If you can still reproduce this problem, please open a new issue and I'll be more than happy to help!
