### ISSUE TITLE
Filter git_changelog by file

### ISSUE THREAD

**Issue by xlorepdarkhelm** [OddBloke/sphinx-git#41]
I would love it if git_changelog was able to only show the relevant git log entries associated with the file the  Directive is generating output for (or by being able to specify the module to look for).

This would be able to figure out which revisions affected a specific module, and only show those revisions,

For instance, if I have a module named `main.py`, and I am using `.. git_changelog::` possibly with a `:module:` attribute in the documentation for that file, the list of entries that are generated are only for `main.py`, and will skip any entries that did not affect that particular file.

**Comment by kadrach** [comment]
Turns out this was added a long time ago already, see daa168fafd27527031627ff84eeb3151a529a44f.

The last release on PyPi is a few months before that commit, so you need to install from source.

Once done, this works:

```rst
.. git_changelog::
    :filename_filter: somefile.txt
```

**Comment by xlorepdarkhelm** [comment]
Cool, thanks for the info.

**Comment by languitar** [comment]
Is there any chance to always use the current source file name for this purpose with the aim to create a file-local changelog using `rst_epilog`?
